spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/webshop
    driverClassName: org.postgresql.Driver

liquibase:
  changelog:
    location: classpath:/database/changelog-master.xml
  schema: public

session:
  expirationSeconds: 600

server:
  port: 10000

endpoint-protection:
  protectedEndpoints:
  - pathPattern: /account
    method: GET

loginSession:
  cleanup:
    intervalMillis: 10000